/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafo;

import java.awt.Color;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;


/**
 *
 * @author Jefferson
 */
public class Grafos extends javax.swing.JFrame {
    String botaoPrimario;
    String botaoSecundario;
    String botaoFalhaPrimario;
    String botaoFalhaSecundario;
    int cont=0;
    int metrica=1;
    
   
    Dijkstra d= new Dijkstra();
        
    
    
    public Grafos() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jL = new javax.swing.JLabel();
        jbtnBLU = new javax.swing.JButton();
        jbtnPOA = new javax.swing.JButton();
        jbtnFLO = new javax.swing.JButton();
        jbtnBSB = new javax.swing.JButton();
        jtx = new javax.swing.JTextField();
        jbtnCUR = new javax.swing.JButton();
        jbtnRBP = new javax.swing.JButton();
        jbtnLON = new javax.swing.JButton();
        jbtnCMP = new javax.swing.JButton();
        jbtnRJO = new javax.swing.JButton();
        jbtnBEL = new javax.swing.JButton();
        jbtnSPO = new javax.swing.JButton();
        jbtnNTL = new javax.swing.JButton();
        jbtnSJC = new javax.swing.JButton();
        jbtnBHO = new javax.swing.JButton();
        jbtnBAU = new javax.swing.JButton();
        jbtnCPG = new javax.swing.JButton();
        jbtnCUI = new javax.swing.JButton();
        jbtnMAN = new javax.swing.JButton();
        jbtnSLV = new javax.swing.JButton();
        jbtnREC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MetricaA = new javax.swing.JMenuItem();
        MetricaB = new javax.swing.JMenuItem();
        MetricaC = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        removePOA = new javax.swing.JMenuItem();
        removeFLO = new javax.swing.JMenuItem();
        removeBLU = new javax.swing.JMenuItem();
        removeCUR = new javax.swing.JMenuItem();
        removeLON = new javax.swing.JMenuItem();
        removeBAU = new javax.swing.JMenuItem();
        removeSPO = new javax.swing.JMenuItem();
        removeCMP = new javax.swing.JMenuItem();
        removeSJC = new javax.swing.JMenuItem();
        removeRBP = new javax.swing.JMenuItem();
        removeRJO = new javax.swing.JMenuItem();
        removeBHO = new javax.swing.JMenuItem();
        removeSPO6 = new javax.swing.JMenuItem();
        removeSPO7 = new javax.swing.JMenuItem();
        removeCUI = new javax.swing.JMenuItem();
        removeSLV = new javax.swing.JMenuItem();
        removeMAN = new javax.swing.JMenuItem();
        removeBEL = new javax.swing.JMenuItem();
        removeNTL = new javax.swing.JMenuItem();
        removeREC = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuPOAFLO = new javax.swing.JMenuItem();
        jMenuPOABLU = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jL);
        jL.setBounds(0, 330, 290, 200);

        jbtnBLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/BLU.png"))); // NOI18N
        jbtnBLU.setContentAreaFilled(false);
        jbtnBLU.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnBLU.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnBLU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBLUMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnBLU);
        jbtnBLU.setBounds(430, 410, 40, 30);

        jbtnPOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/POA.png"))); // NOI18N
        jbtnPOA.setAlignmentX(0.5F);
        jbtnPOA.setAutoscrolls(true);
        jbtnPOA.setBorderPainted(false);
        jbtnPOA.setContentAreaFilled(false);
        jbtnPOA.setMargin(new java.awt.Insets(2, 14, 7, 14));
        jbtnPOA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPOAMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnPOA);
        jbtnPOA.setBounds(430, 480, 40, 30);

        jbtnFLO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/FLO.png"))); // NOI18N
        jbtnFLO.setContentAreaFilled(false);
        jbtnFLO.setMargin(new java.awt.Insets(2, 14, 7, 14));
        jbtnFLO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnFLOMouseClicked(evt);
            }
        });
        jbtnFLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFLOActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFLO);
        jbtnFLO.setBounds(500, 440, 40, 30);

        jbtnBSB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/bsb.png"))); // NOI18N
        jbtnBSB.setContentAreaFilled(false);
        jbtnBSB.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnBSB.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnBSB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBSBMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnBSB);
        jbtnBSB.setBounds(510, 260, 40, 30);

        jtx.setEditable(false);
        getContentPane().add(jtx);
        jtx.setBounds(0, 330, 290, 200);

        jbtnCUR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/cur.png"))); // NOI18N
        jbtnCUR.setContentAreaFilled(false);
        jbtnCUR.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnCUR.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnCUR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCURMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnCUR);
        jbtnCUR.setBounds(490, 380, 40, 30);

        jbtnRBP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/RBP.png"))); // NOI18N
        jbtnRBP.setContentAreaFilled(false);
        jbtnRBP.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnRBP.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnRBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRBPMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnRBP);
        jbtnRBP.setBounds(500, 310, 40, 30);

        jbtnLON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/lon.png"))); // NOI18N
        jbtnLON.setContentAreaFilled(false);
        jbtnLON.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnLON.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnLON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLONMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnLON);
        jbtnLON.setBounds(440, 370, 40, 30);

        jbtnCMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/CMP.png"))); // NOI18N
        jbtnCMP.setContentAreaFilled(false);
        jbtnCMP.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnCMP.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnCMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCMPMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnCMP);
        jbtnCMP.setBounds(530, 340, 40, 30);

        jbtnRJO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/rjo.png"))); // NOI18N
        jbtnRJO.setContentAreaFilled(false);
        jbtnRJO.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnRJO.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnRJO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRJOMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnRJO);
        jbtnRJO.setBounds(630, 350, 40, 30);

        jbtnBEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/bel.png"))); // NOI18N
        jbtnBEL.setContentAreaFilled(false);
        jbtnBEL.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnBEL.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnBEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBELMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnBEL);
        jbtnBEL.setBounds(510, 90, 40, 30);

        jbtnSPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/spo.png"))); // NOI18N
        jbtnSPO.setContentAreaFilled(false);
        jbtnSPO.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnSPO.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnSPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSPOMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnSPO);
        jbtnSPO.setBounds(530, 370, 40, 30);

        jbtnNTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/ntl.png"))); // NOI18N
        jbtnNTL.setContentAreaFilled(false);
        jbtnNTL.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnNTL.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnNTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnNTLMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnNTL);
        jbtnNTL.setBounds(730, 120, 40, 30);

        jbtnSJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/sjc.png"))); // NOI18N
        jbtnSJC.setContentAreaFilled(false);
        jbtnSJC.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnSJC.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnSJC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSJCMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnSJC);
        jbtnSJC.setBounds(570, 360, 40, 30);

        jbtnBHO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/bho.png"))); // NOI18N
        jbtnBHO.setContentAreaFilled(false);
        jbtnBHO.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnBHO.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnBHO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBHOMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnBHO);
        jbtnBHO.setBounds(590, 300, 40, 30);

        jbtnBAU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/bau.png"))); // NOI18N
        jbtnBAU.setContentAreaFilled(false);
        jbtnBAU.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnBAU.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnBAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBAUMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnBAU);
        jbtnBAU.setBounds(460, 340, 40, 30);

        jbtnCPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/cpg.png"))); // NOI18N
        jbtnCPG.setContentAreaFilled(false);
        jbtnCPG.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnCPG.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnCPG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCPGMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnCPG);
        jbtnCPG.setBounds(390, 320, 40, 30);

        jbtnCUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/cui.png"))); // NOI18N
        jbtnCUI.setContentAreaFilled(false);
        jbtnCUI.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnCUI.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnCUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCUIMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnCUI);
        jbtnCUI.setBounds(360, 240, 40, 30);

        jbtnMAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/man.png"))); // NOI18N
        jbtnMAN.setContentAreaFilled(false);
        jbtnMAN.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnMAN.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnMAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnMANMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnMAN);
        jbtnMAN.setBounds(300, 120, 40, 30);

        jbtnSLV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/slv.png"))); // NOI18N
        jbtnSLV.setContentAreaFilled(false);
        jbtnSLV.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnSLV.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnSLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSLVMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnSLV);
        jbtnSLV.setBounds(670, 240, 40, 30);

        jbtnREC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/rec.png"))); // NOI18N
        jbtnREC.setContentAreaFilled(false);
        jbtnREC.setMargin(new java.awt.Insets(2, 12, 8, 14));
        jbtnREC.setPreferredSize(new java.awt.Dimension(213, 240));
        jbtnREC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRECMouseClicked(evt);
            }
        });
        getContentPane().add(jbtnREC);
        jbtnREC.setBounds(740, 170, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafo/img/mini-motos-quadriciclo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 0, 690, 530);

        jMenu1.setText("Metrica    ");

        MetricaA.setText("A");
        MetricaA.setSelected(true);
        MetricaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MetricaAMousePressed(evt);
            }
        });
        jMenu1.add(MetricaA);

        MetricaB.setText("B");
        MetricaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MetricaBMousePressed(evt);
            }
        });
        jMenu1.add(MetricaB);

        MetricaC.setText("C");
        MetricaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MetricaCMousePressed(evt);
            }
        });
        jMenu1.add(MetricaC);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Falha");

        jMenu5.setText("Pops");

        removePOA.setText("POA");
        removePOA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removePOAMousePressed(evt);
            }
        });
        jMenu5.add(removePOA);

        removeFLO.setText("FLO");
        removeFLO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeFLOMousePressed(evt);
            }
        });
        jMenu5.add(removeFLO);

        removeBLU.setText("BLU");
        removeBLU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeBLUMousePressed(evt);
            }
        });
        jMenu5.add(removeBLU);

        removeCUR.setText("CUR");
        removeCUR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeCURMousePressed(evt);
            }
        });
        jMenu5.add(removeCUR);

        removeLON.setText("LON");
        removeLON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeLONMousePressed(evt);
            }
        });
        jMenu5.add(removeLON);

        removeBAU.setText("BAU");
        removeBAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeBAUMousePressed(evt);
            }
        });
        jMenu5.add(removeBAU);

        removeSPO.setText("SPO");
        removeSPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeSPOMousePressed(evt);
            }
        });
        jMenu5.add(removeSPO);

        removeCMP.setText("CMP");
        removeCMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeCMPMousePressed(evt);
            }
        });
        jMenu5.add(removeCMP);

        removeSJC.setText("SJC");
        removeSJC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeSJCMousePressed(evt);
            }
        });
        jMenu5.add(removeSJC);

        removeRBP.setText("RBP");
        removeRBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeRBPMousePressed(evt);
            }
        });
        jMenu5.add(removeRBP);

        removeRJO.setText("RJO");
        removeRJO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeRJOMousePressed(evt);
            }
        });
        jMenu5.add(removeRJO);

        removeBHO.setText("BHO");
        removeBHO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeBHOMousePressed(evt);
            }
        });
        jMenu5.add(removeBHO);

        removeSPO6.setText("BSB");
        removeSPO6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeSPO6MousePressed(evt);
            }
        });
        jMenu5.add(removeSPO6);

        removeSPO7.setText("CPG");
        removeSPO7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeSPO7MousePressed(evt);
            }
        });
        jMenu5.add(removeSPO7);

        removeCUI.setText("CUI");
        removeCUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeCUIMousePressed(evt);
            }
        });
        jMenu5.add(removeCUI);

        removeSLV.setText("SLV");
        removeSLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeSLVMousePressed(evt);
            }
        });
        jMenu5.add(removeSLV);

        removeMAN.setText("MAN");
        removeMAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeMANMousePressed(evt);
            }
        });
        jMenu5.add(removeMAN);

        removeBEL.setText("BEL");
        removeBEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeBELMousePressed(evt);
            }
        });
        jMenu5.add(removeBEL);

        removeNTL.setText("NTL");
        removeNTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeNTLMousePressed(evt);
            }
        });
        jMenu5.add(removeNTL);

        removeREC.setText("REC");
        removeREC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeRECMousePressed(evt);
            }
        });
        jMenu5.add(removeREC);

        jMenu3.add(jMenu5);

        jMenu6.setText("Enlace");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu6MousePressed(evt);
            }
        });

        jMenuPOAFLO.setText("POA-FLO");
        jMenuPOAFLO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuPOAFLOMousePressed(evt);
            }
        });
        jMenu6.add(jMenuPOAFLO);

        jMenuPOABLU.setText("POA-BLU");
        jMenuPOABLU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuPOABLUMousePressed(evt);
            }
        });
        jMenu6.add(jMenuPOABLU);

        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 807, 588);
    }// </editor-fold>//GEN-END:initComponents
boolean tes=true;
    private void jbtnBLUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBLUMouseClicked
    
     //  ImageIcon icone = new ImageIcon("POA.jpg");
      // Image image = icone.getImage();
       
      if(jbtnBLU.getBorder().equals(evt)){
      Border thickBorder = new LineBorder(Color.blue, 2);
     jbtnBLU.setBorder(thickBorder);
     tes=false;
       }else{
          System.out.print("teste");
          tes=true;
      jbtnBLU.setSize(40,40);
       }
        
       // if(erro){
            cont++;
            
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="BLU";
                 jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null || botaoPrimario == null){
                botaoPrimario="BLU";
                botaoSecundario=null;
                cont--;
            }else {
                botaoSecundario="BLU";
               // jL.setText(botaoPrimario+" "+botaoSecundario);
            
            }
                //System.out.println("BLU");
                
               
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
               System.out.print(resp);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
           
       // }//else{
            //  c.remove(2);
       //     erro=true;
        
       // }
    }//GEN-LAST:event_jbtnBLUMouseClicked

    private void jbtnPOAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPOAMouseClicked
    //  if(erro){
            cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="POA";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="POA";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="POA";
                System.out.println("POA");
                if(cont>=2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
           
        /*}else{
            //  c.remove(2);
            erro=true;
        
        }*/
    }//GEN-LAST:event_jbtnPOAMouseClicked

    private void jbtnFLOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnFLOMouseClicked
        // if(erro){
            cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="FLO";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="FLO";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="FLO";
                System.out.println("flo");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
           
     /*   }else{
            
            erro=true;
        
        }*/
    }//GEN-LAST:event_jbtnFLOMouseClicked

    private void jbtnFLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFLOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFLOActionPerformed

    private void MetricaAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetricaAMousePressed
     System.out.println("A");
        metrica=1;
    }//GEN-LAST:event_MetricaAMousePressed

    private void MetricaBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetricaBMousePressed
        System.out.print("metricaB");
        metrica=2;
    }//GEN-LAST:event_MetricaBMousePressed

    private void MetricaCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetricaCMousePressed
        System.out.print("metricaC");
        metrica=3;
    }//GEN-LAST:event_MetricaCMousePressed

    private void removePOAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removePOAMousePressed
       if(!botaoFalhaPrimario.equals("POA") && !botaoFalhaSecundario.equals("POA")){
        String t=  d.removeVertice("POA",botaoFalhaPrimario, botaoFalhaSecundario,metrica);
         jL.setText("<html>Vertice de (Origem): "+botaoFalhaPrimario+"<br>Vertice de (Destino): "+botaoFalhaSecundario+
                "<br><br>Falha no Vertice POA <br><br>"+t);
    } else{
            jL.setText("<html>Caminho não pode ser definido pós o vertice de Origem ou de Destino está com Falha</html>");
       }
    }//GEN-LAST:event_removePOAMousePressed

    private void removeFLOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeFLOMousePressed
       if(!botaoFalhaPrimario.equals("FLO") && !botaoFalhaSecundario.equals("FLO")){
        String t=  d.removeVertice("FLO", botaoFalhaPrimario, botaoFalhaSecundario,metrica);
         jL.setText("<html>Vertice de (Origem): "+botaoFalhaPrimario+"<br>Vertice de (Destino): "+botaoFalhaSecundario+
                "<br><br>Falha no Vertice FLO <br><br>"+t);
       }else{
           jL.setText("<html>Caminho não pode ser definido pós o vertice de Origem ou de Destino está com Falha</html>");
       }
    }//GEN-LAST:event_removeFLOMousePressed

    private void jMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MousePressed
       
    }//GEN-LAST:event_jMenu6MousePressed

    private void jMenuPOAFLOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPOAFLOMousePressed
         System.out.println("REMOVE");
        String t=  d.removeAresta("POA", "FLO",botaoFalhaPrimario,botaoFalhaSecundario,metrica);
         jL.setText("<html>Vertice de (Origem): "+botaoFalhaPrimario+"<br>Vertice de (Destino): "+botaoFalhaSecundario+
                "<br><br>Falha na Aresta de POA -> FLO <br><br>"+t);
    }//GEN-LAST:event_jMenuPOAFLOMousePressed

    private void jbtnCURMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCURMouseClicked
               cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="CUR";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="CUR";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="CUR";
                System.out.println("CUR");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnCURMouseClicked

    private void jbtnBSBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBSBMouseClicked
        cont++;
        if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="BSB";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="BSB";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="BSB";
                System.out.println("BSB");
                if(cont==2){
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnBSBMouseClicked

    private void removeBLUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBLUMousePressed
         if(!botaoFalhaPrimario.equals("BLU") && !botaoFalhaSecundario.equals("BLU")){
            String t=  d.removeVertice("BLU", botaoFalhaPrimario, botaoFalhaSecundario,metrica);
            jL.setText("<html>Vertice de (Origem): "+botaoFalhaPrimario+"<br>Vertice de (Destino): "+botaoFalhaSecundario+
                    "<br><br>Falha no Vertice BLU <br><br>"+t);
        }else{
           jL.setText("<html>Caminho não pode ser definido pós o vertice de Origem ou de Destino está com Falha</html>");
       }
    }//GEN-LAST:event_removeBLUMousePressed

    private void jbtnRBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRBPMouseClicked
        cont++;
        if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="RBP";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="RBP";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="RBP";
                System.out.println("RBP");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnRBPMouseClicked

    private void jbtnLONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLONMouseClicked
         cont++;
        if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="LON";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="LON";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="LON";
                System.out.println("LON");
                if(cont==2){
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnLONMouseClicked

    private void jbtnCMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCMPMouseClicked
         cont++;
        if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="CMP";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="CMP";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="CMP";
                System.out.println("CMP");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnCMPMouseClicked

    private void jbtnRJOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRJOMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="RJO";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="RJO";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="RJO";
                System.out.println("RJO");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnRJOMouseClicked

    private void jbtnBELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBELMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="BEL";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="BEL";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="BEL";
                System.out.println("BEL");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnBELMouseClicked

    private void jbtnSPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSPOMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="SPO";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="SPO";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="SPO";
                System.out.println("SPO");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnSPOMouseClicked

    private void jbtnNTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnNTLMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="NTL";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="NTL";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="NTL";
                System.out.println("NTL");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnNTLMouseClicked

    private void jbtnSJCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSJCMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="SJC";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="SJC";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="SJC";
                System.out.println("SJC");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnSJCMouseClicked

    private void jbtnBHOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBHOMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="BHO";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="BHO";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="BHO";
                System.out.println("BHO");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnBHOMouseClicked

    private void jbtnBAUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBAUMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="BAU";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="BAU";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="BAU";
                System.out.println("BAU");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnBAUMouseClicked

    private void jbtnCPGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCPGMouseClicked
              cont++;
            if(botaoPrimario == null || botaoPrimario == ""){
                botaoPrimario ="CPG";
                jL.setText("Vértice Selecionado (Origem): "+botaoPrimario);
                botaoSecundario=null;
            }else if(botaoSecundario != null ||  botaoPrimario == ""){
                botaoPrimario="CPG";
                botaoSecundario=null;
                cont--;
            }else botaoSecundario="CPG";
                System.out.println("CPG");
                if(cont==2){
                
                String resp;
                resp = d.PROCURAR(botaoPrimario,botaoSecundario,metrica);
                jL.setText("<html>Vértice Selecionado (Origem): "+botaoPrimario+"<br>Vertice selecionado (Destino): "+botaoSecundario+"<br><br>"+resp);
                cont=0;
                botaoFalhaPrimario=botaoPrimario;
                botaoFalhaSecundario=botaoSecundario;
                botaoPrimario=null;
                botaoSecundario=null;
                }else{
                    
                }
    }//GEN-LAST:event_jbtnCPGMouseClicked

    private void jbtnCUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCUIMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCUIMouseClicked

    private void jbtnMANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMANMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnMANMouseClicked

    private void jbtnSLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSLVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSLVMouseClicked

    private void jbtnRECMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRECMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRECMouseClicked

    private void removeCURMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCURMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCURMousePressed

    private void removeLONMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeLONMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeLONMousePressed

    private void removeBAUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBAUMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBAUMousePressed

    private void removeSPOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSPOMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSPOMousePressed

    private void removeCMPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCMPMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCMPMousePressed

    private void removeSJCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSJCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSJCMousePressed

    private void removeRBPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeRBPMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeRBPMousePressed

    private void removeRJOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeRJOMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeRJOMousePressed

    private void removeBHOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBHOMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBHOMousePressed

    private void removeSPO6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSPO6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSPO6MousePressed

    private void removeSPO7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSPO7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSPO7MousePressed

    private void removeCUIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCUIMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCUIMousePressed

    private void removeSLVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSLVMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSLVMousePressed

    private void removeMANMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMANMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeMANMousePressed

    private void removeBELMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBELMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBELMousePressed

    private void removeNTLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeNTLMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeNTLMousePressed

    private void removeRECMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeRECMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeRECMousePressed

    private void jMenuPOABLUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPOABLUMousePressed
       
        String t=  d.removeAresta("POA", "BLU",botaoFalhaPrimario,botaoFalhaSecundario,metrica);
         jL.setText("<html>Vertice de (Origem): "+botaoFalhaPrimario+"<br>Vertice de (Destino): "+botaoFalhaSecundario+
                "<br><br>Falha na Aresta de POA -> BLU <br><br>"+t);
    }//GEN-LAST:event_jMenuPOABLUMousePressed
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       //JFrame t= new JFrame();
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new Grafos().setVisible(true);
            }
        });
        
    }
   /* public void montar(){
          desenhoLinha l=new desenhoLinha();
        l.setBounds(50,100,100,1000);
        l.setOpaque(false);
     
        panel1.add(l);
       panel1.repaint();
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MetricaA;
    private javax.swing.JMenuItem MetricaB;
    private javax.swing.JMenuItem MetricaC;
    private javax.swing.JLabel jL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuPOABLU;
    private javax.swing.JMenuItem jMenuPOAFLO;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JButton jbtnBAU;
    private javax.swing.JButton jbtnBEL;
    private javax.swing.JButton jbtnBHO;
    private javax.swing.JButton jbtnBLU;
    private javax.swing.JButton jbtnBSB;
    private javax.swing.JButton jbtnCMP;
    private javax.swing.JButton jbtnCPG;
    private javax.swing.JButton jbtnCUI;
    private javax.swing.JButton jbtnCUR;
    private javax.swing.JButton jbtnFLO;
    private javax.swing.JButton jbtnLON;
    private javax.swing.JButton jbtnMAN;
    private javax.swing.JButton jbtnNTL;
    private javax.swing.JButton jbtnPOA;
    private javax.swing.JButton jbtnRBP;
    private javax.swing.JButton jbtnREC;
    private javax.swing.JButton jbtnRJO;
    private javax.swing.JButton jbtnSJC;
    private javax.swing.JButton jbtnSLV;
    private javax.swing.JButton jbtnSPO;
    private javax.swing.JTextField jtx;
    private javax.swing.JMenuItem removeBAU;
    private javax.swing.JMenuItem removeBEL;
    private javax.swing.JMenuItem removeBHO;
    private javax.swing.JMenuItem removeBLU;
    private javax.swing.JMenuItem removeCMP;
    private javax.swing.JMenuItem removeCUI;
    private javax.swing.JMenuItem removeCUR;
    private javax.swing.JMenuItem removeFLO;
    private javax.swing.JMenuItem removeLON;
    private javax.swing.JMenuItem removeMAN;
    private javax.swing.JMenuItem removeNTL;
    private javax.swing.JMenuItem removePOA;
    private javax.swing.JMenuItem removeRBP;
    private javax.swing.JMenuItem removeREC;
    private javax.swing.JMenuItem removeRJO;
    private javax.swing.JMenuItem removeSJC;
    private javax.swing.JMenuItem removeSLV;
    private javax.swing.JMenuItem removeSPO;
    private javax.swing.JMenuItem removeSPO6;
    private javax.swing.JMenuItem removeSPO7;
    // End of variables declaration//GEN-END:variables
}
